### ISSUE TITLE
Distilbert texts_from_folder

### ISSUE THREAD

**Issue by law826** [amaiya/ktrain#273] opened 2020-11-14 17:35 UTC
This following seems to be running fine. Running on ktrain 0.25.0.

```
(x_train, y_train), (x_test, y_test), preproc = text.texts_from_folder(
            data_dir, maxlen=500, preprocess_mode='bert', 
            train_test_names=['train', 'test'],
            classes=['pos', 'neg'])
```

However, switching to distilbert doesn't:

```
(x_train, y_train), (x_test, y_test), preproc = text.texts_from_folder(
            data_dir, maxlen=500, preprocess_mode='distilbert', 
            train_test_names=['train', 'test'],
            classes=['pos', 'neg'])
```

Which causes this error: 

```
detected encoding: utf-8
preprocessing train...
language: en
train sequence lengths:
        mean : 303
        95percentile : 557
        99percentile : 782
Traceback (most recent call last):
  File "NLP_run_training.py", line 56, in <module>
    nlptrain = NLPtrain(args.pathology, args.model_version, run_splits=args.run_splits)
  File "NLP_run_training.py", line 40, in __init__
    classes=['pos', 'neg'])
  File "/opt/miniconda3/envs/env_nlp/lib/python3.6/site-packages/ktrain/text/data.py", line 115, in texts_from_folder
    trn = preproc.preprocess_train(x_train, y_train, verbose=verbose)
  File "/opt/miniconda3/envs/env_nlp/lib/python3.6/site-packages/ktrain/text/preprocessor.py", line 918, in preprocess_train
    verbose=verbose)
  File "/opt/miniconda3/envs/env_nlp/lib/python3.6/site-packages/ktrain/text/preprocessor.py", line 329, in hf_convert_examples
    pb = progress_bar(texts, parent=mb)
  File "/opt/miniconda3/envs/env_nlp/lib/python3.6/site-packages/fastprogress/fastprogress.py", line 226, in __init__
    super().__init__(gen, total, display, leave, parent, master)
  File "/opt/miniconda3/envs/env_nlp/lib/python3.6/site-packages/fastprogress/fastprogress.py", line 24, in __init__
    parent.add_child(self)
  File "/opt/miniconda3/envs/env_nlp/lib/python3.6/site-packages/fastprogress/fastprogress.py", line 264, in add_child
    self.child.prefix = f'Epoch {self.main_bar.last_v+1}/{self.main_bar.total} :'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

**Comment by amaiya** [comment] 2020-11-14 19:16
Hello:

First, I need to point out that tuples of NumPy arrays are **NOT** returned when selecting 'distilbert' as the model.  When you do `text_classifier('bert', ...`, the **texts_from_folder** function returns a tuple of NumPy arrays.  However, when you do `text_classifier('distilbert' ...`, the **texts_from_folder** function returns `TransformerDataset` objects.  As shown in the tutorials and example notebooks, you need to change the call to this for things to work:

```python
trn, val, preproc = text.texts_from_folder(
            data_dir, maxlen=500, preprocess_mode='distilbert', 
            train_test_names=['train', 'test'],
            classes=['pos', 'neg'])
```

However, I think the error you're getting is different and occurring even **before** this issue above even happens.

Based on your setting of `train_test_names` and `classes`, your `data_dir` folder should look like this:
```
    ├── datadir
    │   ├── train
    │   │   ├── pos       # folder containing documents of class pos
    │   │   ├── neg       # folder containing documents of class neg
    │   └── test 
    │       ├── pos       # folder containing documents of class pos
    │       ├── neg       # folder containing documents of class neg
```

**Are you sure your `data_dir` folder is structured like this when trying to use distilbert?**    I don't see a reason why 'distilbert' would throw that error and 'bert' would not, as the code that crawls the folder to collect documents is exactly the same.

What happens when you run this?  What does `x_train`, `y_train`, `x_test`, and `y_test` contain?

```python
import os.path
from sklearn.datasets import load_files
train_b = load_files(os.path.join(data_dir, train_str), shuffle=True, categories=classes)
test_str = train_test_names[1]
test_b = load_files(os.path.join(data_dir,  test_str), shuffle=False, categories=classes)
x_train = train_b.data
y_train = train_b.target
x_test = test_b.data
y_test = test_b.target
```

**Comment by law826** [comment] 2020-11-14 22:13
Thanks for your prompt response and for pointing out the issue about the call. As you predicted, the error seems to arise before this. 

I have been using the BERT setting for a long time with no issues, so I think the data is structured properly, like the way you have outlined above. When I run your code, I get the following:

x_train and x_test are both lists of strings from my text files.
y_train and y_test are numpy arrays containing 0 and 1. 
x_train/y_train and x_test/y_test pairs are equal in length.

**Comment by amaiya** [comment] 2020-11-14 22:55
I  ran an example myself and everything in `texts_from_folder` works correctly when selecting `distilbert`.  So, I don't think this is a bug in the **ktrain** code.   

I think the problem is that you're using a very old version of `fastprogress` that includes [this bug](https://github.com/fastai/fastprogress/pull/59).   If you upgrade to the latest version of `fastprogress` that includes a fix for this problem, everything should work.  

For good measure, you may want to create a new virtual environment and install **ktrain** and its dependencies from scratch.

**Closed** 2020-11-16 19:21 UTC

**Comment by law826** [comment] 2020-11-16 20:31
I got it to run through with no issue after the fastprogress update. Thanks so much! Great work on this repo.
