### ISSUE TITLE
Save model in steps, (12 hours for an epoch) learner.fit_onecycle(8e-5, 1)

### ISSUE THREAD

**Issue by raqueeb** [amaiya/ktrain#293] opened 2020-12-11 13:47 UTC
Hello Arun,

Fantastic job! I can't even save full one epoch, takes more than 12 hours for an epoch, how do I save and train more and save.

I read your FAQ, but I can't finish even one cycle training to save it in ktrain.get_predictor(model, preproc).save('/tmp/my_predictor')

I assume here preprocess = t.

I was hoping for at least saving steps, and half of an epoch.

I'm using your huggingface A3 example. [My notebook is here](https://github.com/raqueeb/nlp_bangla/blob/master/transformers_bert_Bangla.ipynb).

Thank you.

Rakib, Bangladesh

**Comment by amaiya** [comment] 2020-12-11 14:28
Duplicate of #276

**Comment by amaiya** [comment] 2020-12-11 14:32
Hello:  This has been already requested as an enhancement.  That said, BERT is a large model that takes a long time to train and your training set has over 350K examples.  One of the advantages of pretrained models is that you can achieve good performance with a smaller training set.  For the time being, I would suggest sampling the dataset and seeing what performance you get.  There is probably some degree of redundancy in a dataset that large.

**Closed by amaiya** 2020-12-11 14:32 UTC
