### ISSUE TITLE
KeyError: 'loss' while trying out some examples

### ISSUE THREAD

**Issue by ShoubhikBanerjee** [amaiya/ktrain#220] opened 2020-08-01 15:28 UTC
I was trying out for experiments from [this](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/examples/text/20newsgroup-distilbert.ipynb)  and [this](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/tutorials/tutorial-A3-hugging_face_transformers.ipynb) urls.

**My transformer version is : 3.0.2**

And I am getting error while trying to find the learning rate from the laerner : 

`simulating training for different learning rates... this may take a few moments...
Train for 22326 steps
Epoch 1/2
    0/22326 [..............................] - ETA: 0s

---------------------------------------------------------------------------

InvalidArgumentError                      Traceback (most recent call last)

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_v2.py in on_batch(self, step, mode, size)
    783       try:
--> 784         yield batch_logs
    785       finally:

21 frames

InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  logits and labels must be broadcastable: logits_size=[6,5] labels_size=[6,6]
	 [[node loss/output_1_loss/softmax_cross_entropy_with_logits (defined at /usr/local/lib/python3.6/dist-packages/ktrain/lroptimize/lrfinder.py:119) ]]
	 [[Reshape_415/_286]]
  (1) Invalid argument:  logits and labels must be broadcastable: logits_size=[6,5] labels_size=[6,6]
	 [[node loss/output_1_loss/softmax_cross_entropy_with_logits (defined at /usr/local/lib/python3.6/dist-packages/ktrain/lroptimize/lrfinder.py:119) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference_distributed_function_53893]

Function call stack:
distributed_function -> distributed_function

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)

/usr/local/lib/python3.6/dist-packages/ktrain/lroptimize/lrfinder.py in on_batch_end(self, batch, logs)
     32 
     33         # Log the loss
---> 34         loss = logs['loss']
     35         self.batch_num +=1
     36         self.avg_loss = self.beta * self.avg_loss + (1-self.beta) *loss

KeyError: 'loss'`

Any guess what is the issue ? 

It would be very grateful if you help me to solve it. Thank You.

**Comment by ShoubhikBanerjee** [comment] 2020-08-01 15:52
it occured when the classes=[int_type, int_type, int_type].  Any way arround for it?

**Comment by amaiya** [comment] 2020-08-01 16:52
You provided URLs to two example notebooks.  Both of them have been verified to work on Google Colab, which suggests there something odd about your data.

It looks like there is a mismatch between the way the model is configured and the labels in your dataset.

Please provide more information on what your labels look like in your dataset.  What does `y_train` look like prior to supplying it to `preprocess_train` or `texts_from_array`?

**Comment by ShoubhikBanerjee** [comment] 2020-08-02 08:36
My `df.head()`  looks like this:


![image](https://user-images.githubusercontent.com/44529417/89119060-ecd2b100-d4c8-11ea-80e4-74d6657dd7a3.png)


and my `df.info()`  looks like this:

![image](https://user-images.githubusercontent.com/44529417/89119014-72099600-d4c8-11ea-931e-366a8837092b.png)


And my learner initialization  is as follows : 

**import ktrain 
from ktrain import text
MODEL_NAME = 'distilbert-base-uncased'
t = text.Transformer(MODEL_NAME, maxlen=512,class_names=['1','2','3','4','5'])
trn = t.preprocess_train(TRAINING_X, TRAINING_Y)
val = t.preprocess_test(VALIDATION_X, VALIDATION_Y)
model = t.get_classifier()
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=10)**

My Training Code is :  

**learner.fit_onecycle(3e-5, 6)**

Then after 1 epoch I am getting error : 

![image](https://user-images.githubusercontent.com/44529417/89119109-37542d80-d4c9-11ea-8cac-4fd65336eb73.png)

Can you help me to resolve the issue?

**Comment by amaiya** [comment] 2020-08-02 12:47
The problem is that your labels must start with 0. So, if you have 5 labels, then the labels must be `[0,1,2,3,4]`, instead of `[1,2,3,4,5]`.

Assuming `TRAINING_Y` and `VALIDATION_Y` are NumPy arrays like `[5,1,4,2,5]`, you should be able to simple do; `TRAINING_Y = TRAINING_Y-1` to fix things, for example.

I will add a better error check for this situation in the next version of *ktrain*, so keeping this issue open.

**Comment by ShoubhikBanerjee** [comment] 2020-08-02 13:46
Okay, but just one more concern : 

My `TRAINING_Y ` is **NumPy array of strings**  like ['1']

Therefore, I have used **class_names=['1','2','3','4','5']**

So why do we need to convert it to [0,1,2,3,4] ?  I am bit confused here.

**Comment by amaiya** [comment] 2020-08-02 14:23
Are you sure that `TRAINING_Y` contains strings? Please check more closely.  The error isn't really possible when it contains strings.

The error you described can only occur when `TRAINING_Y` contains integers in which case the fix above works.  If `TRAINING_Y` contains strings, then everything works.  The example below replicates what you described (with 4 classes not 5) when Y contains integers in string format and, as you can see, everything works:

```python
# load text data
categories = ['alt.atheism', 'soc.religion.christian','comp.graphics', 'sci.med']
from sklearn.datasets import fetch_20newsgroups
train_b = fetch_20newsgroups(subset='train', categories=categories, shuffle=True)
test_b = fetch_20newsgroups(subset='test',categories=categories, shuffle=True)
(x_train, y_train) = (train_b.data, train_b.target)
(x_test, y_test) = (test_b.data, test_b.target)

# transformations to replicate your dataset if `y_train` and `y_test` are strings
y_train = y_train+1
y_test = y_test+1
y_train = list(map(str, y_train))
y_test = list(map(str, y_test))

# build, train, and validate model (Transformer is wrapper around transformers library)
import ktrain
from ktrain import text
MODEL_NAME = 'distilbert-base-uncased'
t = text.Transformer(MODEL_NAME, maxlen=500, class_names=['1','2', '3', '4'])
trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_test, y_test)
model = t.get_classifier()
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=6)
learner.fit_onecycle(5e-5, 1)
```

The `class_names` parameter simply maps indices to string labels (e.g., `0->'negative'`, `1->'positive'`).  But, if  Y contains strings, then the labels are extracted from Y instead of `class_names`.

Also,if you're confused, I would recommend you look at STEP 1 of [this tutorial](https://nbviewer.jupyter.org/github/amaiya/ktrain/blob/master/tutorials/tutorial-A3-hugging_face_transformers.ipynb), as everything is explained there.

**Comment by ShoubhikBanerjee** [comment] 2020-08-02 14:59
Thanx a lot for your help, I am trying it again, and keep updated about this. Thanx Sir!

**Comment by ShoubhikBanerjee** [comment] 2020-08-03 05:41
Hi, I have gone through the code and modified some changes.

But the problem is that, when I run the same code with smaller input size (Say, 50K rows from CSV), it works fine.

But when I am trying to load nearly 150K rows from CSV it gave an error after running the 1st epoch.

For more details, you can find my dataset [here](https://drive.google.com/file/d/1OMUSpziV-H_IrPwWDMxzcKgI12gqKbm5/view?usp=sharing)  and colab notebook [here](https://colab.research.google.com/drive/1EMey-dO_vtxhQEWBQzu4Z4V85-K8QhP8?usp=sharing).

I have kept the error as it is so that you can see the logs. 

Is it possible for you to go and check it there? Thanks.

**Comment by amaiya** [comment] 2020-08-03 14:04
Thanks for letting me know.  If you upgrade *ktrain* to v0.19.2, it will work.  

A few other comments:
1. You can use the `stratify` argument to `train_test_split` to ensure the label distributions are consistent.  It seemed like validation set only contained two of the classes (1 and 2). so you should double-check this.
2. Since you are predicting numerical ratings, I would recommend treating this as a text regression problem instead of a classification problem.  Use integer values for labels but omit the `class_names` argument to treat as regression. Another user did this by transforming ratings from -2 to +2 instead of 1 through 5 for Yelp reviews. The pretrained model is [available here](https://huggingface.co/spentaur/yelp).

I will close this issue for now, but feel free to reply (or open new issue) if you have further problems.

**Closed by amaiya** 2020-08-03 14:04 UTC
