### ISSUE TITLE
TypeError: normalize() argument 2 must be str, not int

### ISSUE THREAD

**Issue by hduanac** [amaiya/ktrain#291] opened 2020-12-10 06:08 UTC
Hi,

I met a problem while doing preprocessing with BERT. Does anyone know how to solve it?
Error presented below.

Thanks.

![image](https://user-images.githubusercontent.com/73025868/101727811-2ad38780-3af0-11eb-90ed-8151de682562.png)
![image](https://user-images.githubusercontent.com/73025868/101727866-43dc3880-3af0-11eb-9eff-cf6aaa2e70fe.png)
![image](https://user-images.githubusercontent.com/73025868/101727888-4ccd0a00-3af0-11eb-9291-692ca96d26dc.png)

**Comment by amaiya** [comment] 2020-12-10 13:29
What does your dataset look like (i.e., what does `data_train.head()` output)?

**Comment by hduanac** [comment] 2020-12-11 02:31
> What does your dataset look like (i.e., what does `data_train.head()` output)?

Hi, Arun! Thanks for your comment. 

The dataset consists of two columns of 'Reviews' and the corresponding 'Sentiment' as shown below. 

Thank you!

![image](https://user-images.githubusercontent.com/73025868/101854126-d84fa500-3b9b-11eb-92dc-5476ca58332c.png)

**Comment by amaiya** [comment] 2020-12-11 03:27
I wasn't able to reproduce your problem using the latest version of **ktrain**. For instance, the following works:
```python
import ktrain
from ktrain import text
categories = ['alt.atheism', 'soc.religion.christian',
             'comp.graphics', 'sci.med']
from sklearn.datasets import fetch_20newsgroups
train_b = fetch_20newsgroups(subset='train',
   categories=categories, shuffle=True, random_state=42)
x_train = train_b.data
y_train = train_b.target
import pandas as pd
import numpy as np
df = pd.DataFrame({'text': x_train, 'label': y_train})
trn, val, preproc = text.texts_from_df(train_df=df, text_column='text',label_columns='label',
                                          preprocess_mode='bert',
                                          maxlen=350)
```

Maybe try ensuring you're using the latest versions of **ktrain** and its dependencies by re-installing everything into a new virtual environment.

**Comment by hduanac** [comment] 2020-12-11 04:57
> I wasn't able to reproduce your problem using the latest version of **ktrain**. For instance, the following works:
> 
> ```python
> import ktrain
> from ktrain import text
> categories = ['alt.atheism', 'soc.religion.christian', 'comp.graphics', 'sci.med']
> from sklearn.datasets import fetch_20newsgroups
> train_b = fetch_20newsgroups(subset='train', categories=categories, shuffle=True, random_state=42)
> x_train = train_b.data
> y_train = train_b.target
> y_train = [train_b.target_names[y] for y in y_train]
> import pandas as pd
> df = pd.DataFrame({'text': x_train, 'label': y_train})
> trn, val, preproc = text.texts_from_df(train_df=df, text_column='text',label_columns='label',
>                                           preprocess_mode='bert',
>                                           maxlen=350)
> ```
> 
> Maybe try ensuring you're using the latest versions of **ktrain** and its dependencies by re-installing everything into a new virtual environment.

Thank you, Arun! The error disappeared after reducing the size of dataset from 25,000 to 2,000.   :)

**Comment by amaiya** [comment] 2020-12-11 05:14
Hi,
There shouldn't be any problem with a dataset of 25K examples. The IMDB dataset is that size for example. I suspect one or more of the examples in the set you threw out is causing a problem with the `keras_bert` tokenizer.  If you post the dataset somewhere, I'm happy to take a look. I will close this issue for now. Thanks.

**Closed by amaiya** 2020-12-11 05:14 UTC

**Comment by Tejash-Shah** [comment] 2021-02-13 23:02
I figured out where this error is coming from so I thought to add a comment here and help users of this package. 

This dataset contains a review in **Reviews** column which is purely integer, in this case, 0  and that's why there is ```TypeError: normalize() argument 2 must be str, not int``` error. It's coming from ```keras_bert/tokenizer.py``` and ktrain internally uses ```keras_bert``` 

If you do something like this ```train = train[train['Reviews']!=0].copy()``` the error will go away.  If you reduce the dataset from 25,000 to 2,000 and it worked because those 2,000 did not contain integer review :) Hope this helps.
