### ISSUE TITLE
Models trained with ktrain do not work with Flask, uWSGI and NGINX

### ISSUE THREAD

**Issue by laxmimerit** [amaiya/ktrain#182] opened 2020-06-20 19:22 UTC
Hi,
I am using `ktrain` to replace some of my `Keras` built models in production deployment. I have noticed a problem with models trained with `ktrain`. I think I might need to set some extra params in my NGINX and uWSGI while using the `ktrain` because I can't simply replace older models with ktrain models. 

I am using Flask, uWSGI, and NGINX to deploy my models. This setup is already in place with models trained with traditional Keras and TF2. But If I replace my Text Classification model with ktrain then it stops working.

I have checked it individually with Flask and uWSGI, it is working fine till now. But as soon as I add NGINX server setup it stops working. There something happening inside ktrain APIs which is breaking it because if I do not use ktrain APIs it is working perfectly fine with all setup. 

At the front end, it is saying Server Timeout Error. I have checked internal logs to identify the issue and it is happening because uWSGI is not returning anything to NGINX. Although, If I run only Flask and uWSGI with ktrain model, it runs. I also tried to increase timeout time to 5m, 10m, 30m even after that connection timeout is coming. It is happening only when I can API which uses ktrain models. Other APIs which do not use ktrain models are working perfectly fine. i.e. Only those APIs are not working which uses ktrain models and others are working. 

I had one more problem with ktrain on Flask server but I have resolved that by turning off auto_reload on file change. Because it seems ktrain download or write something in the local directory that is why Flask was reloading when I call prediction. Although, this is resolved.

I have tried with BERT, DistilBERT, Fast Text, GRU and so many other ways to figure out why It is not working with NGINX. Can you add your thoughts about what could be the reason?

I have also created a [User Guide] (https://drive.google.com/file/d/1VW421zkmXkiQdoO1NWhVe21QOgVhVUnc/view?usp=sharing)
to show you server settings. It will help to identify exact problem. If you can look at it and add your thoughts, it would be really great help. I want to use `ktrain` in production but got stuck here.

**Comment by amaiya** [comment] 2020-06-20 20:35
Happy to help, but can you please provide complete instructions on what you're doing? I see in the guide that you're installing *ktrain*, but where is the *ktrain* code that makes the predictions?. For instance, there is a reference to `mlmodel.py`.  What do the contents of `mlmodel.py` looks like?

**Comment by laxmimerit** [comment] 2020-06-20 20:58
Thanks a lot for your quick reply. Here is code.
```
import ktrain
import os

os.environ["CUDA_VISIBLE_DEVICES"] = "-1" # use only CPU in prediction

predictor = ktrain.load_predictor('fasttext') #tested it with BERT, DistilBERT, GRU as well


def get_prediction(x):
	pred = predictor.predict([x])
	return pred[0]
```

If I do not use predictor then it starts working for this API. If I use traditional Keras model, it works fine.

**Comment by amaiya** [comment] 2020-06-20 21:02
What does the Keras version that works look like?

**Comment by laxmimerit** [comment] 2020-06-20 21:02
Sorry did not get you?

**Comment by amaiya** [comment] 2020-06-20 21:05
You said earlier it works when you use replace *ktrain* with a vanilla Keras model. What does `mlmodel.py` look like when you make predictions with Vanilla Keras.   You can redact, as necessary.

**Comment by laxmimerit** [comment] 2020-06-20 21:12
Well. It's only traditional way. Like saving and loading.
`model = load_model('model.h5')` and then `predict`.
The problem is happening at this predict stage. 

Prediction is taking just a few milliseconds in ktrain even after that it is getting hanged. Everything is working with `ktrain` If is use only Flask and uWSGI. It is getting broken only If I add NGINX. 

If this doesn't help. Let me know. I will try to post more info and codes.

**Comment by amaiya** [comment] 2020-06-20 21:24
In the Keras version that works for you, are you using `tf.Keras` or are you using **stand-alone** Keras with TensorFlow 2 backend?

**Comment by laxmimerit** [comment] 2020-06-20 21:37
It is Keras with TF2.1 `tf.keras`.

**Comment by amaiya** [comment] 2020-06-20 21:48
*ktrain* is a thin wrapper for `tf.Keras` and models trained with *ktrain* are just `tf.Keras` models.   If you look at the *ktrain* prediction code (espcially for a model like `fasttext`) it is quite simple and simply invokes the same `tf.Keras` calls that you're invoking for your vanilla Keras models.  So,there's no reason that it should not work if your vanilla Keras model works.   For instance, for `fasttext`, the `predictor.predict` method just preprocesses the raw text   with standard Keras methods like `texts_to_sequences` and `pad_sequences`. Then, it simply invokes `model.predict`.
One thing you can try is to take the model you trained with *ktrain* and make the predictions using only `tf.Keras` and see if it works.   That may shed some light on what is going on.

I will also look into it further and let you know if additional questions come up.

**Comment by laxmimerit** [comment] 2020-06-20 21:57
Thanks a lot. I was also wondering what could go wrong. Thanks a lot for your help. This is really great wrapper. I am using it a lot nowadays. I will update you if I get the solution.

**Comment by amaiya** [comment] 2020-06-22 02:31
Hi @laxmimerit : I've confirmed that the issues  you are experiencing are **not** related to *ktrain*. 
In my tests, running the model with `tf.keras` (in TensorFlow 2.1) behaves exactly the same as running the model with *ktrain* `Predictor` instance (also TensorFlow 2.1).

I think the problem you experienced may be a threading issue. I did notice that, if using NGINX, the `.ini` file must be set to the following to work even if using only `tf.Keras`:
```
master = false
processes = 1
```
The above is only necessary when NGINX is used.  When using UWSGI without NGINX, `master=true; processes=5` works.  This seems to affect `tf.Keras`,  not *ktrain* specifically.   I'm afraid I'm not familiar enough with nginx to know why.  See this guide for more information, though:
[https://zkf85.github.io/2018/12/03/flask-uwsgi-nginx-deploy](https://zkf85.github.io/2018/12/03/flask-uwsgi-nginx-deploy)

As I mentioned earlier, *ktrain* is a pretty thin wrapper around `tf.Keras`, so nothing in it should cause problems with deploying successfully.  In fact, *ktrain* models are used in a number of different production settings (e.g., AWS ElasticBeanStalk, etc.).

I'll close this issue for now, but please do continue replying to this thread if you have additional questions or additional information after trying my earlier recommendations. It would be interesting to know what is different in the the setup you have that works.  It seems there must be something different in that setup.   You have not shared the actual Flask code you're using (e..g, it's not clear how/where `get_prediction` is called in your code), so maybe it's something related to that.

**Closed by amaiya** 2020-06-22 02:31 UTC

**Comment by amaiya** [comment] 2020-06-22 02:56
See also [this stackoverflow post](https://stackoverflow.com/questions/49255545/flask-application-giving-504-timeout-through-uwsgi-and-nginx).

**Comment by laxmimerit** [comment] 2020-06-22 08:03
Thanks a lot. How silly of me. I have missed it. Yes you are right. It is
the problem of multithreading. I am still not sure how my Keras code was
working on another server. I might have done some settings there long time
ago.
Thanks a lot for your help. It is much appreciated. Now it is working.
