### ISSUE TITLE
Issue while importing ktrain : module 'tensorflow_core.keras.activations' has no attribute 'swish'  

### ISSUE THREAD

**Issue by skayasanoori** [amaiya/ktrain#255] opened 2020-09-23 13:41 UTC
ktrain==0.17.3

Error:

AttributeError                            Traceback (most recent call last)
<ipython-input-9-ccbda6fc29a3> in <module>()
----> 1 import ktrain

/usr/local/lib/python3.6/dist-packages/transformers/activations_tf.py in <module>()
     51     "gelu": tf.keras.layers.Activation(gelu),
     52     "relu": tf.keras.activations.relu,
---> 53     "swish": tf.keras.activations.swish,
     54     "gelu_new": tf.keras.layers.Activation(gelu_new),
     55     "mish": tf.keras.layers.Activation(mish),

AttributeError: module 'tensorflow_core.keras.activations' has no attribute 'swish'

**Comment by amaiya** [comment] 2020-09-23 13:57
Duplicate of #254.

The latest version of `transformers` (3.2 just released yesterday) [evidently no longer supports TensorFlow 2.1 and below](https://github.com/huggingface/transformers/issues/7333).  I will update the **ktrain** documentation accordingly in the next released.

You'll need to either downgrade `transformers` or upgrade `tensorflow` to 2.2 or 2.3.   Regardless of what you choose, you should also upgrade to the latest version of   **ktrain** (v0.21.x), as this version can be used with any version of TensorFlow and is no  longer pinned to TensorFlow 2.1 on Python 3.6/3.7 systems.

**Comment by zhenpingli** [comment] 2020-10-04 06:27
> he latest version of `transformers` (3.2 just released yesterday) [evidently no longer supports TensorFlow 2.1 and below](https://github.com/huggingface/transformers/issues/7333). I will update the **ktrain** documentation accordingly in the next release.
> 
> You'll need to either downgrade `transformers` to 3.1 or upgrade `tensorflow` to 2.2 or 2.3.

 get the right answer

**Comment by stevenfongyilee** [comment] 2020-10-30 02:48
Hi there, still running into this issue, even with tensorflow==2.3.1 and transformers==3.4.0 and ktrain==0.23.2.

**Comment by zhenpingli** [comment] 2020-10-30 02:52
> Hi there, still running into this issue, even with tensorflow==2.3.1 and transformers==3.4.0 and ktrain==0.23.2.

https://github.com/amaiya/ktrain/issues/255#issuecomment-719137336
You'll need to either downgrade transformers to 3.1 or upgrade  3.1 ，but you got 3.4,try it again and if you need i will check my pip list and conda env list ,sent to you if it still in my computer

**Comment by alxgal** [comment] 2021-01-08 21:08
> Duplicate of #254.
> 
> The latest version of `transformers` (3.2 just released yesterday) [evidently no longer supports TensorFlow 2.1 and below](https://github.com/huggingface/transformers/issues/7333). I will update the **ktrain** documentation accordingly in the next release.
> 
> You'll need to either downgrade `transformers` to 3.1 or upgrade `tensorflow` to 2.2 or 2.3. Regardless of what you choose, you should also upgrade to the latest version of **ktrain** (v0.21.x), as this version can be used with any version of TensorFlow and is no longer pinned to TensorFlow 2.1 on Python 3.6/3.7 systems.

I tried this but I keep getting other error messages depending on the version of transformers that I install:
Version 4.1.1: `AttributeError: module 'tensorflow_core.python.keras.api._v2.keras.activations' has no attribute 'swish'` (as expected and mentioned in the thread)
Version 3.4.0: `ModuleNotFoundError: No module named 'sacremoses'` (when I try to pip install sacramoses, it tells me that the requirement is already satisfied)
Version 3.1.0: `ImportError: cannot import name 'add_start_docstrings_to_callable' from 'transformers.file_utils' (C:\Users\user\AppData\Roaming\Python\Python37\site-packages\transformers\file_utils.py)` 

I'm kind of at a loss right now bc I seemingly tried everything...
Any help would be very much appreciated

**Comment by waqarkaleemkhan** [comment] 2021-04-26 17:58
If someone other has the same issue upgrade TensorFlow it worked for me

**Closed** 2021-10-09 12:58 UTC
